In [10]:
import requests

In [23]:
url = "https://www.thesportsdb.com/api/v1/json/3/searchevents.php?e=Arsenal_vs_Chelsea&s=2016-2017"

response= requests.get(url)
json_data = response.json() 
response=response.json()
print(response)

{'event': [{'idEvent': '679698', 'idAPIfootball': None, 'strEvent': 'Arsenal vs Chelsea', 'strEventAlternate': 'Chelsea @ Arsenal', 'strFilename': 'FA Cup 2017-05-27 Arsenal vs Chelsea', 'strSport': 'Soccer', 'idLeague': '4482', 'strLeague': 'FA Cup', 'strLeagueBadge': 'https://r2.thesportsdb.com/images/media/league/badge/vk7isd1598802862.png', 'strSeason': '2016-2017', 'strDescriptionEN': '', 'strHomeTeam': 'Arsenal', 'strAwayTeam': 'Chelsea', 'intHomeScore': '2', 'intRound': '200', 'intAwayScore': '1', 'intSpectators': '89472', 'strOfficial': None, 'strTimestamp': None, 'dateEvent': '2017-05-27', 'dateEventLocal': '2017-05-27', 'strTime': '17:30:00', 'strTimeLocal': '', 'strGroup': None, 'idHomeTeam': '133604', 'strHomeTeamBadge': None, 'idAwayTeam': '133610', 'strAwayTeamBadge': None, 'intScore': None, 'intScoreVotes': None, 'strResult': '', 'idVenue': None, 'strVenue': None, 'strCountry': None, 'strCity': None, 'strPoster': None, 'strSquare': None, 'strFanart': None, 'strThumb': None, 'strBanner': None, 'strMap': None, 'strTweet1': '', 'strVideo': 'https://www.youtube.com/watch?v=OOkzIJ2Ge2M', 'strStatus': None, 'strPostponed': 'no', 'strLocked': 'unlocked'}, {'idEvent': '508788', 'idAPIfootball': None, 'strEvent': 'Arsenal vs Chelsea', 'strEventAlternate': 'Chelsea @ Arsenal', 'strFilename': 'English Premier League 2016-09-24 Arsenal vs Chelsea', 'strSport': 'Soccer', 'idLeague': '4328', 'strLeague': 'English Premier League', 'strLeagueBadge': 'https://r2.thesportsdb.com/images/media/league/badge/dsnjpz1679951317.png', 'strSeason': '2016-2017', 'strDescriptionEN': None, 'strHomeTeam': 'Arsenal', 'strAwayTeam': 'Chelsea', 'intHomeScore': '3', 'intRound': '6', 'intAwayScore': '0', 'intSpectators': '0', 'strOfficial': None, 'strTimestamp': None, 'dateEvent': '2016-09-24', 'dateEventLocal': None, 'strTime': '16:30:00+00:00', 'strTimeLocal': None, 'strGroup': None, 'idHomeTeam': '133604', 'strHomeTeamBadge': None, 'idAwayTeam': '133610', 'strAwayTeamBadge': None, 'intScore': None, 'intScoreVotes': None, 'strResult': None, 'idVenue': None, 'strVenue': None, 'strCountry': None, 'strCity': None, 'strPoster': None, 'strSquare': None, 'strFanart': None, 'strThumb': None, 'strBanner': None, 'strMap': None, 'strTweet1': None, 'strVideo': None, 'strStatus': None, 'strPostponed': 'no', 'strLocked': 'unlocked'}]}

In [24]:
import json
import pandas as pd
df=pd.DataFrame(json_data['event'])

In [25]:
df

,idEvent,idAPIfootball,strEvent,strEventAlternate,strFilename,strSport,idLeague,strLeague,strLeagueBadge,strSeason,...,strSquare,strFanart,strThumb,strBanner,strMap,strTweet1,strVideo,strStatus,strPostponed,strLocked
0,679698,None,Arsenal vs Chelsea,Chelsea @ Arsenal,FA Cup 2017-05-27 Arsenal vs Chelsea,Soccer,4482,FA Cup,https://r2.thesportsdb.com/images/media/league...,2016-2017,...,None,None,None,None,None,,https://www.youtube.com/watch?v=OOkzIJ2Ge2M,None,no,unlocked
1,508788,None,Arsenal vs Chelsea,Chelsea @ Arsenal,English Premier League 2016-09-24 Arsenal vs C...,Soccer,4328,English Premier League,https://r2.thesportsdb.com/images/media/league...,2016-2017,...,None,None,None,None,None,NaN,NaN,None,no,unlocked

In [26]:
df.head()

,idEvent,idAPIfootball,strEvent,strEventAlternate,strFilename,strSport,idLeague,strLeague,strLeagueBadge,strSeason,...,strSquare,strFanart,strThumb,strBanner,strMap,strTweet1,strVideo,strStatus,strPostponed,strLocked
0,679698,None,Arsenal vs Chelsea,Chelsea @ Arsenal,FA Cup 2017-05-27 Arsenal vs Chelsea,Soccer,4482,FA Cup,https://r2.thesportsdb.com/images/media/league...,2016-2017,...,None,None,None,None,None,,https://www.youtube.com/watch?v=OOkzIJ2Ge2M,None,no,unlocked
1,508788,None,Arsenal vs Chelsea,Chelsea @ Arsenal,English Premier League 2016-09-24 Arsenal vs C...,Soccer,4328,English Premier League,https://r2.thesportsdb.com/images/media/league...,2016-2017,...,None,None,None,None,None,NaN,NaN,None,no,unlocked

In [27]:
df.shape

(2, 46)

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 46 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   idEvent            2 non-null      str
 1   idAPIfootball      0 non-null      object
 2   strEvent           2 non-null      str
 3   strEventAlternate  2 non-null      str
 4   strFilename        2 non-null      str
 5   strSport           2 non-null      str
 6   idLeague           2 non-null      str
 7   strLeague          2 non-null      str
 8   strLeagueBadge     2 non-null      str
 9   strSeason          2 non-null      str
 10  strDescriptionEN   1 non-null      str
 11  strHomeTeam        2 non-null      str
 12  strAwayTeam        2 non-null      str
 13  intHomeScore       2 non-null      str
 14  intRound           2 non-null      str
 15  intAwayScore       2 non-null      str
 16  intSpectators      2 non-null      str
 17  strOfficial        0 non-null      object
 18  strTimestamp       0 non-null      object
 19  dateEvent          2 non-null      str
 20  dateEventLocal     1 non-null      str
 21  strTime            2 non-null      str
 22  strTimeLocal       1 non-null      str
 23  strGroup           0 non-null      object
 24  idHomeTeam         2 non-null      str
 25  strHomeTeamBadge   0 non-null      object
 26  idAwayTeam         2 non-null      str
 27  strAwayTeamBadge   0 non-null      object
 28  intScore           0 non-null      object
 29  intScoreVotes      0 non-null      object
 30  strResult          1 non-null      str
 31  idVenue            0 non-null      object
 32  strVenue           0 non-null      object
 33  strCountry         0 non-null      object
 34  strCity            0 non-null      object
 35  strPoster          0 non-null      object
 36  strSquare          0 non-null      object
 37  strFanart          0 non-null      object
 38  strThumb           0 non-null      object
 39  strBanner          0 non-null      object
 40  strMap             0 non-null      object
 41  strTweet1          1 non-null      str
 42  strVideo           1 non-null      str
 43  strStatus          0 non-null      object
 44  strPostponed       2 non-null      str
 45  strLocked          2 non-null      str
dtypes: object(19), str(27)
memory usage: 868.0+ bytes

In [29]:
df.describe()

,idEvent,idAPIfootball,strEvent,strEventAlternate,strFilename,strSport,idLeague,strLeague,strLeagueBadge,strSeason,...,strSquare,strFanart,strThumb,strBanner,strMap,strTweet1,strVideo,strStatus,strPostponed,strLocked
count,2,0,2,2,2,2,2,2,2,2,...,0,0,0,0,0,1,1,0,2,2
unique,2,0,1,1,2,1,2,2,2,1,...,0,0,0,0,0,1,1,0,1,1
top,679698,NaN,Arsenal vs Chelsea,Chelsea @ Arsenal,FA Cup 2017-05-27 Arsenal vs Chelsea,Soccer,4482,FA Cup,https://r2.thesportsdb.com/images/media/league...,2016-2017,...,NaN,NaN,NaN,NaN,NaN,,https://www.youtube.com/watch?v=OOkzIJ2Ge2M,NaN,no,unlocked
freq,1,NaN,2,2,1,2,1,1,1,2,...,NaN,NaN,NaN,NaN,NaN,1,1,NaN,2,2

In [30]:
df.isnull()

,idEvent,idAPIfootball,strEvent,strEventAlternate,strFilename,strSport,idLeague,strLeague,strLeagueBadge,strSeason,...,strSquare,strFanart,strThumb,strBanner,strMap,strTweet1,strVideo,strStatus,strPostponed,strLocked
0,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,False,False,True,False,False
1,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,False,False

In [31]:
df.isnull().sum()

idEvent              0
idAPIfootball        2
strEvent             0
strEventAlternate    0
strFilename          0
strSport             0
idLeague             0
strLeague            0
strLeagueBadge       0
strSeason            0
strDescriptionEN     1
strHomeTeam          0
strAwayTeam          0
intHomeScore         0
intRound             0
intAwayScore         0
intSpectators        0
strOfficial          2
strTimestamp         2
dateEvent            0
dateEventLocal       1
strTime              0
strTimeLocal         1
strGroup             2
idHomeTeam           0
strHomeTeamBadge     2
idAwayTeam           0
strAwayTeamBadge     2
intScore             2
intScoreVotes        2
strResult            1
idVenue              2
strVenue             2
strCountry           2
strCity              2
strPoster            2
strSquare            2
strFanart            2
strThumb             2
strBanner            2
strMap               2
strTweet1            1
strVideo             1
strStatus            2
strPostponed         0
strLocked            0
dtype: int64

In [32]:
df.fillna("NAN")

,idEvent,idAPIfootball,strEvent,strEventAlternate,strFilename,strSport,idLeague,strLeague,strLeagueBadge,strSeason,...,strSquare,strFanart,strThumb,strBanner,strMap,strTweet1,strVideo,strStatus,strPostponed,strLocked
0,679698,NAN,Arsenal vs Chelsea,Chelsea @ Arsenal,FA Cup 2017-05-27 Arsenal vs Chelsea,Soccer,4482,FA Cup,https://r2.thesportsdb.com/images/media/league...,2016-2017,...,NAN,NAN,NAN,NAN,NAN,,https://www.youtube.com/watch?v=OOkzIJ2Ge2M,NAN,no,unlocked
1,508788,NAN,Arsenal vs Chelsea,Chelsea @ Arsenal,English Premier League 2016-09-24 Arsenal vs C...,Soccer,4328,English Premier League,https://r2.thesportsdb.com/images/media/league...,2016-2017,...,NAN,NAN,NAN,NAN,NAN,NAN,NAN,NAN,no,unlocked

In [33]:
df.isna().sum()

idEvent              0
idAPIfootball        2
strEvent             0
strEventAlternate    0
strFilename          0
strSport             0
idLeague             0
strLeague            0
strLeagueBadge       0
strSeason            0
strDescriptionEN     1
strHomeTeam          0
strAwayTeam          0
intHomeScore         0
intRound             0
intAwayScore         0
intSpectators        0
strOfficial          2
strTimestamp         2
dateEvent            0
dateEventLocal       1
strTime              0
strTimeLocal         1
strGroup             2
idHomeTeam           0
strHomeTeamBadge     2
idAwayTeam           0
strAwayTeamBadge     2
intScore             2
intScoreVotes        2
strResult            1
idVenue              2
strVenue             2
strCountry           2
strCity              2
strPoster            2
strSquare            2
strFanart            2
strThumb             2
strBanner            2
strMap               2
strTweet1            1
strVideo             1
strStatus            2
strPostponed         0
strLocked            0
dtype: int64

In [34]:
df.columns

Index(['idEvent', 'idAPIfootball', 'strEvent', 'strEventAlternate',
       'strFilename', 'strSport', 'idLeague', 'strLeague', 'strLeagueBadge',
       'strSeason', 'strDescriptionEN', 'strHomeTeam', 'strAwayTeam',
       'intHomeScore', 'intRound', 'intAwayScore', 'intSpectators',
       'strOfficial', 'strTimestamp', 'dateEvent', 'dateEventLocal', 'strTime',
       'strTimeLocal', 'strGroup', 'idHomeTeam', 'strHomeTeamBadge',
       'idAwayTeam', 'strAwayTeamBadge', 'intScore', 'intScoreVotes',
       'strResult', 'idVenue', 'strVenue', 'strCountry', 'strCity',
       'strPoster', 'strSquare', 'strFanart', 'strThumb', 'strBanner',
       'strMap', 'strTweet1', 'strVideo', 'strStatus', 'strPostponed',
       'strLocked'],
      dtype='str')

In [37]:
df.index_col='idEvent'

In [38]:
df

,idAPIfootball,strEvent,strEventAlternate,strFilename,strSport,idLeague,strLeague,strLeagueBadge,strSeason,strDescriptionEN,...,strSquare,strFanart,strThumb,strBanner,strMap,strTweet1,strVideo,strStatus,strPostponed,strLocked
idEvent,,,,,,,,,,,,,,,,,,,,,
679698,None,Arsenal vs Chelsea,Chelsea @ Arsenal,FA Cup 2017-05-27 Arsenal vs Chelsea,Soccer,4482,FA Cup,https://r2.thesportsdb.com/images/media/league...,2016-2017,,...,None,None,None,None,None,,https://www.youtube.com/watch?v=OOkzIJ2Ge2M,None,no,unlocked
508788,None,Arsenal vs Chelsea,Chelsea @ Arsenal,English Premier League 2016-09-24 Arsenal vs C...,Soccer,4328,English Premier League,https://r2.thesportsdb.com/images/media/league...,2016-2017,NaN,...,None,None,None,None,None,NaN,NaN,None,no,unlocked

In [39]:
df['idAPIfootball'].dtype

dtype('O')

In [40]:
df['strFilename']

idEvent
679698                 FA Cup 2017-05-27 Arsenal vs Chelsea
508788    English Premier League 2016-09-24 Arsenal vs C...
Name: strFilename, dtype: str

In [43]:
df.rename(columns={'idLeague':'League'},inplace=True)

In [44]:
df

,idAPIfootball,strEvent,strEventAlternate,strFilename,strSport,League,strLeague,strLeagueBadge,strSeason,strDescriptionEN,...,strSquare,strFanart,strThumb,strBanner,strMap,strTweet1,strVideo,strStatus,strPostponed,strLocked
idEvent,,,,,,,,,,,,,,,,,,,,,
679698,None,Arsenal vs Chelsea,Chelsea @ Arsenal,FA Cup 2017-05-27 Arsenal vs Chelsea,Soccer,4482,FA Cup,https://r2.thesportsdb.com/images/media/league...,2016-2017,,...,None,None,None,None,None,,https://www.youtube.com/watch?v=OOkzIJ2Ge2M,None,no,unlocked
508788,None,Arsenal vs Chelsea,Chelsea @ Arsenal,English Premier League 2016-09-24 Arsenal vs C...,Soccer,4328,English Premier League,https://r2.thesportsdb.com/images/media/league...,2016-2017,NaN,...,None,None,None,None,None,NaN,NaN,None,no,unlocked

In [45]:
df.iloc[0:1]# first row

,idAPIfootball,strEvent,strEventAlternate,strFilename,strSport,League,strLeague,strLeagueBadge,strSeason,strDescriptionEN,...,strSquare,strFanart,strThumb,strBanner,strMap,strTweet1,strVideo,strStatus,strPostponed,strLocked
idEvent,,,,,,,,,,,,,,,,,,,,,
679698,None,Arsenal vs Chelsea,Chelsea @ Arsenal,FA Cup 2017-05-27 Arsenal vs Chelsea,Soccer,4482,FA Cup,https://r2.thesportsdb.com/images/media/league...,2016-2017,,...,None,None,None,None,None,,https://www.youtube.com/watch?v=OOkzIJ2Ge2M,None,no,unlocked

In [50]:
df[df['strHomeTeam']=='Arsenal']

,idAPIfootball,strEvent,strEventAlternate,strFilename,strSport,League,strLeague,strLeagueBadge,strSeason,strDescriptionEN,...,strSquare,strFanart,strThumb,strBanner,strMap,strTweet1,strVideo,strStatus,strPostponed,strLocked
idEvent,,,,,,,,,,,,,,,,,,,,,
679698,None,Arsenal vs Chelsea,Chelsea @ Arsenal,FA Cup 2017-05-27 Arsenal vs Chelsea,Soccer,4482,FA Cup,https://r2.thesportsdb.com/images/media/league...,2016-2017,,...,None,None,None,None,None,,https://www.youtube.com/watch?v=OOkzIJ2Ge2M,None,no,unlocked
508788,None,Arsenal vs Chelsea,Chelsea @ Arsenal,English Premier League 2016-09-24 Arsenal vs C...,Soccer,4328,English Premier League,https://r2.thesportsdb.com/images/media/league...,2016-2017,NaN,...,None,None,None,None,None,NaN,NaN,None,no,unlocked

In [52]:
df.dtypes

idAPIfootball        object
strEvent                str
strEventAlternate       str
strFilename             str
strSport                str
League                  str
strLeague               str
strLeagueBadge          str
strSeason               str
strDescriptionEN        str
strHomeTeam             str
strAwayTeam             str
intHomeScore            str
intRound                str
intAwayScore            str
intSpectators           str
strOfficial          object
strTimestamp         object
dateEvent               str
dateEventLocal          str
strTime                 str
strTimeLocal            str
strGroup             object
idHomeTeam              str
strHomeTeamBadge     object
idAwayTeam              str
strAwayTeamBadge     object
intScore             object
intScoreVotes        object
strResult               str
idVenue              object
strVenue             object
strCountry           object
strCity              object
strPoster            object
strSquare            object
strFanart            object
strThumb             object
strBanner            object
strMap               object
strTweet1               str
strVideo                str
strStatus            object
strPostponed            str
strLocked               str
dtype: object